### ISSUE TITLE
why i install pytesseract,show TypeError: integer argument expected, got 'str' error

### ISSUE THREAD

**Issue by jxua** [madmaze/pytesseract#118]
because our company can not use pip install,so i download it in git,then easy_install.but when install,show below error.From 0.1.6 to 0.2.0 all show this error,
![image](https://user-images.githubusercontent.com/22673941/39975367-a52da4b4-5760-11e8-8ade-cb47d3c6ea69.png)   i will wait on-line for it,please help me quicky,thanks

**Comment by int3l** [comment]
You can try to unpack the archive.
1. uncompress the archive
2. cd to the unpacked folder
3. use setup.py directly with either pip or python
```bash
cd <dir_with_setup.py>
# AND
pip install .
# OR
python setup.py install
```

Closing this since this is not a pytesseract specific problem.
It is a deployment issue on Windows + Anaconda platform.
And please read the Installation documentation section (README file) ...

**Comment by jxua** [comment]
when i try use python setup.py install, also this error show

**Comment by jxua** [comment]
try pip install .  also this error
