### ISSUE TITLE
HOCR

### ISSUE THREAD

**Issue by Davesnake** [madmaze/pytesseract#120]
Hi, I need the results in HOCR format, not in TSV, is there a way to achieve that? Thanks in advance

**Comment by int3l** [comment]
@Davesnake I guess you will need to make a custom logic for your specific case, since there is no build in extraction of the hocr file content in pytesseract. Unfortunately I didn't have time to create/test the image_to_hocr function or some similar logic.

You can try to use one of the non-generic function in order to pass the file extension option. For example - please check [line 146](https://github.com/madmaze/pytesseract/blob/master/src/pytesseract.py#L146) for reference. :)
