### ISSUE TITLE
Why Image.open('test.png')?

### ISSUE THREAD

**Issue by guettli** [madmaze/pytesseract#121]
In the readme, I found this example:

> print(pytesseract.image_to_string(Image.open('test.png')))

I do not understand why the file gets loaded into an Image object.

The final call gets done via subprocess. Why not pass the file name "test.png" directly to the command?

I guess the loading and writing of test.png is useless IO and cpu-time which could be avoided if you just pass the path to the command line.

But maybe I am wrong.

**Comment by int3l** [comment]
Hi @guettli ,
we are doing image pre-processing and in order to keep the original image untouched, we create a new one that is modified and saved to the file system.

We can do it in memory, but tesseract itself doesn't support passing images via std-in (or it was the case in the older version). And this is why the old maintainer and author of this wrapper did it with temp files.

**Comment by guettli** [comment]
Thank you for your kind reply.

It's sad that pre processing is needed.

thinking loud: If you look at it in abstract way: you have a bunch of bytes. Reading them does not work. Then you do some magic, and then they are readable .... How to increase information in a bunch of bytes ... I don't get it.

thank you, thomas

**Comment by int3l** [comment]
Sorry, I don't understand the question "how to increase information in a bunch of bytes?".
What do you mean by that?

One of the primary reasons for the pre-processing is to convert most of the unsupported image formats into a single supported format for the tesseract executable. Also the wrapper currently support adding background for all images with transparent background.

There is no magic in all of that. Maybe it's me, but I don't get your point.
