### ISSUE TITLE
pytesseract.image_to_string returns nothing sometimes

### ISSUE THREAD

**Issue by lolonger** [madmaze/pytesseract#136]
I applied pytesseract.image_to_string to two identical images. 
one is generated by Image.save(), one is generated by plt.imsave(). 
It works fine with the plt.save image, however, it always return nothing with the Image.save() image.
I don't know why. 
The images I'm processing look like this, 
![tmp](https://user-images.githubusercontent.com/33473685/42406415-3f6b851c-8175-11e8-8392-04effefd77f7.jpg)

**Comment by lolonger** [comment]
by the way, both the saved images are loaded again by Image.open(), then feed into pytesseract.image_to_string()

**Comment by int3l** [comment]
Hi @lolonger, 
you should compare both images in order to understand what is the difference between the two.
Also the 'Image' class is not from pytesseract - a.k.a your issue is not directly related to this library.
Please refer your question to the [Pillow(PIL) Issue Tracker](https://github.com/python-pillow/Pillow/issues) about why **Image.save** doesn't work the same way like **plt.imsave**.

When I have time, I will try to compare the results.

**Comment by int3l** [comment]
@lolonger Hi, we have support for direct image passing to tesseract, so if you want, you can try to pass the unmodified (relative or absolute) image path like this:

```python
pytesseract.image_to_string('example.jpeg')
```

**Comment by int3l** [comment]
Thank you for the feedback.
