### ISSUE TITLE
Hangup when passing in long list of images

### ISSUE THREAD

**Issue by plestran** [madmaze/pytesseract#167]
Tesseract has the option of taking in a text file containing a list of images to process. This is a much faster way of processing a series of images instead of having to reinitialize Tesseract for each one. 

This module also correctly handled a text file containing a list of images if the list was short (<50). 

`text = pytesseract.image_to_string(txt_file_of_img_file_names, config=tess_config)`

Longer lists of images lead to the module being hung up indefinitely and it never returned a result. Tesseract has no problem handling this larger txt file from the command line. The problem seems to be with pytesseract.

**Comment by int3l** [comment]
Passing a list of images is not officially supported in pytesseract at the moment. It is just a coincidence, because image_to_string accepts the name of image file as plain string (which is needed if you want to bypass the internal image conversions performed by pytesseract).

I am not 100% sure how the batch functionality work in tesseract.
Does it use a single file for the output of all input images?
Changing this to feature request.

**Comment by plestran** [comment]
Yes, it returns a single file for the text it finds across all of those images.

**Comment by cgallay** [comment]
Hi @plestran,
Could you be more specific when you say much faster?

**Comment by makcedward** [comment]
> Hi @plestran,
> Could you be more specific when you say much faster?
> I had the same expectation as you but after a simple test I didn't see much speed up when calling tesseract with a list of image compare to do multiple calls to tesseract.
> I think the tesseract model is small enough that loading it doesn't take much time.

I am facing similar situation. 
Conducted some experiments to improve speed performance. Found out that tesseract take a long time to initialize it. From my experiments, it spends about 20% of time for tesseract initialization.

**Comment by plestran** [comment]
Here are my results from using batching. 

A batch job of 100 images. 
```
real    0m3.511s
user    0m0.000s
sys     0m0.046s
```

If I run each image through Tesseract individually (looping in a bash script) the total time is
```
real    1m0.377s
user    0m0.255s
sys     0m2.769s
```

**Comment by cgallay** [comment]
@plestran Thanks for sharing your result.
after reconducting my test I found something quite similar than you for 1000 images.
Batch job:
```
real      5m23.29s
user      1150.85s
sys       14.78s
```
Image by image:
```
real      7m13.59s
user      1186.78s
sys       30.16s
```

There is definitely a speedup to do when doing it by batch.

**Comment by int3l** [comment]
Hi @plestran and @cgallay  - I will try to create a test case that triggers the hanging behavior in order to debug the issue. I guess that it's related to some kind of buffer/deadlock issue with the piping.
@plestran do you use unix-like OS or Windows for this use case?
Also if it's possible, can you provide a snippet code + single image + image_list file that triggers that behavior?
