### ISSUE TITLE
Digital Number on pytesseract

### ISSUE THREAD

**Issue by RicoLiu** [madmaze/pytesseract#171]
Hi, guys.
I am using **pytesseract** to recognize digital number like this:

![image](https://user-images.githubusercontent.com/12722992/50438741-3c82eb00-092a-11e9-86af-e41e44314c93.png)

 And here is my code:
```python
try
  from PIL import Image
except ImportError:
  import Image
import pytesseract

print(pytesseract.image_to_boxes(Image.open('./image.png')))
```

The result is:

![image](https://user-images.githubusercontent.com/12722992/50438834-badf8d00-092a-11e9-8152-a634f64004e1.png)

I dont know whats wrong with my code.
Or **pytesseract** can not recognize this digital number?
Can anyone help me?

**Comment by int3l** [comment]
Hi @RicoLiu, image_to_boxes result depends on the training data used for training, which by default is just english language. For such kind of images, I guess that you will need to train your own solution or you need to transform the input images to match the training set for the default english traindata.
You can ask on StackOverflow about this since this is not a pytesseract specific issue/problem.

**Comment by RicoLiu** [comment]
Anyway, thank you for suggestion.
