### ISSUE TITLE
timeout support

### ISSUE THREAD

**Issue by starenka** [madmaze/pytesseract#177]
It would be nice, if the OCR functions would support timeouts (on py2k f.e via https://github.com/google/python-subprocess32). Forgive me if there's a `tesseract` binary flag for this as I can't find it :( Cheers.

**Comment by int3l** [comment]
Python 2.7 support will end soon (Jan 1st 2020), so we can add support for the native 3.x timeouts.

**Comment by thushv89** [comment]
I've been battling with this issue for a while now. As I am reading lot of PDFs and tesseract processes become zombies as they couldn't read the PDF for some reason (I'm assuming corrupted PDFs). Overtime this compounds and hogs up all the processes without doing anything. 

I believe this can be fixed by using [communicate(timeout=xx)](https://docs.python.org/3.4/library/subprocess.html#subprocess.Popen.communicate) at [line 189](https://github.com/madmaze/pytesseract/blob/5a39257ad002af88adc037fb3923ca5f26e0f68b/src/pytesseract.py#L189)

**Comment by starenka** [comment]
@int3l the end of support doesn't mean people will magically stop using it ;)

**Comment by int3l** [comment]
@starenka you are absolutely right, but it doesn't seem like a very good idea to add support for the 2.7 version via third party lib that will become legacy pretty soon.

I understand the need for timeout functionality (which also involves manually killing the hanging tesseract process, since the python timeout functionality just unblocks the code execution), but maybe we should add a more elegant solution.

**Comment by vasadhananjay** [comment]
> I've been battling with this issue for a while now. As I am reading lot of PDFs and tesseract processes become zombies as they couldn't read the PDF for some reason (I'm assuming corrupted PDFs). Overtime this compounds and hogs up all the processes without doing anything.
> 
> I believe this can be fixed by using [communicate(timeout=xx)](https://docs.python.org/3.4/library/subprocess.html#subprocess.Popen.communicate) at [line 189](https://github.com/madmaze/pytesseract/blob/5a39257ad002af88adc037fb3923ca5f26e0f68b/src/pytesseract.py#L189).
> 
> I haven't tested it. Please correct me if I'm wrong.

Just ran into this same problem. Can confirm that adding a timeout=XX works fine.

**Comment by int3l** [comment]
Since python-subprocess32 is not entirely cross platform, I will add very basic experimental support for generic timeouts to pytesseract.
