### ISSUE TITLE
Using UZN files

### ISSUE THREAD

**Issue by alexgg94** [madmaze/pytesseract#178]
Is it possible to use an .uzn file (or any other way) to specify from which coordinates of the image the text should be extracted?

**Comment by int3l** [comment]
@alexgg94 Hi,
if tesseract itself supports this, then you can try to pass the appropriate option via pytesseract with the **config** argument. Pytesseract is just a wrapper for the tesseract binary.
Alternatively, you can do manual cropping beforehand, since you already have the coordinates.
Feel free to reopen or post a new issue if you have any problems with pytesseract.

**Comment by Marouaneghoulami** [comment]
Hi, i have tried the config (--psm 4) with pytesseract it doesnt seem to extract what i want, rather it extrcat all of the text.
1. is there any other way to do that from within pytesseract ?
2. is there any workaround to pass the command directly to Tesseradr engine ?
Thanks in advance.
