### ISSUE TITLE
tessedit_char_whitelist

### ISSUE THREAD

**Issue by StormS0** [madmaze/pytesseract#179]
How to set tessedit_char_whitelist for pytesseract .
example tessedit_char_whitelist = 0123456
this is my code , not work 
code = pytesseract.image_to_string(image,config ="-c tessedit_char_whitelist = 0123456789")

**Comment by int3l** [comment]
Hi @StormS0 
I guess that the problem in your particular example is that you use space between the **=** sign and the name of the parameter, and the value.
So for example, try to remove the spaces around the equal sign.
```python
code = pytesseract.image_to_string(image, config ="-c tessedit_char_whitelist=0123456789")
```

Closing, since this is not a pytesseract issue.
Feel free to reopen if you have any problems.

**Comment by bedna-KU** [comment]
I have same issue with tesseract 4.0.0 with tesseract 4.1.0 work OK.

**Comment by int3l** [comment]
@bedna-KU Thank you for the information. I may try to file an issue on the Tesseract-OCR project related to this specific usage. The other option is for pytesseract to modify the user config input, but I prefer to not alter the user input. We may consider a warning if the version is 4.0.0 or less.
