### ISSUE TITLE
Method `image_to_html`

### ISSUE THREAD

**Issue by nok** [madmaze/pytesseract#218]
**Problem**

Sometimes it's difficult to analyse, compare and evaluate the results of Tesseract.

- How good is the recognition?
  - Which page segmentation mode is the best?
  - Which OCR engine is the best?
- How is the confidence of each segmentation?
- Where in the image are the bounding boxes?

**Solution**

I would like to gather the results of the method `image_to_data(output_type=Output.DICT)` and generate a standalone HTML site where the results are shown in a canvas element.

**Limitations**

- Tesseract 3.05+ (because of the use of method `image_to_data`)
- Image data type: JPEG, GIF, PNG (because of the limited browser support ([source](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support)))
- Testing is limited

---

What do you think about a visual representation? And is `pytesseract` the right place for this requirement or is it out of scope, because I'm not sure. For me `pytesseract` is low level API which is a good design. What do you think?

**Comment by int3l** [comment]
Since pytesseract gets the data from tesseract and does it in specific format, we can have something like `generate_html_report` or `data_to_html_report` or anything else. But as far as I can tell - you need something that can output a static content in some specific HTML form. I can also see this functionality as a standalone program/script that utilizes pytesseract.

**Comment by IsNotMyIP** [comment]
Sorry reopening this again.

I think he is asking to a test mode, more than HTML generator.
Usually I directly use:

`cv2.imshow('',image)
cv2.waitkey(0)`
So I can check what I've drawn.

Could we be interested in adding a feature like this one?
