### ISSUE TITLE
Petition to change license to Apache 2.0 (to match tesseract-ocr)

### ISSUE THREAD

**Issue by joshmcgrath08** [madmaze/pytesseract#237]
I want to use tesseract, and in turn pytesseract, but I don't want to include a GPLv3-licensed package before I know what I plant to do with my project.

Has any consideration been given to using a more permissive license such as MIT? Tesseract uses [Apache 2.0](https://github.com/tesseract-ocr/tesseract/blob/master/LICENSE), which is a fairly permissive license as well.

**Comment by madmaze** [comment]
This issue has come up in the past, I would be OK following tesseract's approach with Apache 2.0. 

@int3l thoughts?

**Comment by int3l** [comment]
Hi, sorry for the delay.
@madmaze I agree with you, but keep in mind that I am not very proficient with the legal aspects. This is why I pinged you. And since I just help with the maintenance work, I guess that maybe we should ask at least the top contributors to vote or?

 As I said, I am not a pro with the licensing stuff, but from what I researched, it seems that GPLv3 is compatible with Apache 2.0: [GNU - License Compatibility and Relicensing](https://www.gnu.org/licenses/license-compatibility.en.html)

The initial license was GPLv3 (stated by the original author of pytesseract) and this is why we have it as the current license.

**Comment by madmaze** [comment]
Agreed, i think at the moment the top 3 contributors are: you, @h, and I.  A vote sounds like a good idea, perhaps we should have a limited duration, since I suspect we will not get every contributor to vote.

**Comment by madmaze** [comment]
## Hello fellow pytesseract contributors:
@int3l, @h, @madmaze, @johnthagen, @REMitchell, @ceccoemi, @ELToulemonde, @Sr4l, @nok, @1cph93, @2press, @BSVogler, @CarpyCar, @dAnjou, @integer, @jbochi, @jflesch, @johnfrancisgit, @jsreid13, @lasfter, @paintdog, @paulfurley, @ryanzhou7, @sagark, @streamnsight, @techtonik

### Background
It has come up a couple of times that pytesseract is currently licensed under GPLv3 which is different from `tesseract-ocr`'s Apache 2.0 licensing. GPLv3 states that any application linking to a GPLv3 work is considered a derived "Combined Work", which must also be licensed under GPLv3. This makes it difficult for using this library in any applications not covered by GPLv3 and therefore limits it's use. 

### Proposed Change
To simplify this, we propose changing the license of *pytesseract* to [Apache 2.0](https://github.com/tesseract-ocr/tesseract/blob/master/LICENSE).

Please comment below with an **aye** or **nay** vote. 

Voting will be closed on **December 1st**, hopefully providing plenty of time for everyone to voice their opinions.

**Comment by int3l** [comment]
aye

**Comment by jflesch** [comment]
nay (but according to Git I don't have any line of code left in pytesseract so my vote doesn't matter)

**Comment by jflesch** [comment]
> Voting will be closed on December 1st, hopefully providing plenty of time for everyone to voice their opinions.

I think I must clarify one thing for the other people voting here. This kind of change is not a matter of vote or opinion. To change the license, you need the **complete unanimity** of all contributors having currently some code in pytesseract. Everyone must agree. Otherwise, a single line of GPL will contaminate back the whole pytesseract as GPL. If someone doesn't vote, you can't change the license either. The only way around that is rewriting the code coming from contributors who don't want their code to switch to the Apache license or didn't vote.

While I assume this is what you meant here, I think it's important for people to know precisely the consequences of their vote.

**Comment by 2press** [comment]
aye

**Comment by ceccoemi** [comment]
aye

**Comment by integer** [comment]
aye

**Comment by Sr4l** [comment]
aye

I really like the idea of Copyleft licenses like GPL, but in this case, a library I am totally okay with a more permissive license.

**Comment by respecht** [comment]
Aye

**Comment by REMitchell** [comment]
Aye

**Comment by johnthagen** [comment]
I support adopting a more permissive license.

**Comment by BSVogler** [comment]
aye

**Comment by dAnjou** [comment]
aye

**Comment by johnthagen** [comment]
> @johnthagen, is that an aye or a nay?

aye

**Comment by ELToulemonde** [comment]
Aye

**Comment by int3l** [comment]
@jflesch Thank you for the clarification. This is why I did git blame - those are the last remaining contributors which haven't voted yet and which have unmodified/non refactored code: @streamnsight, @nok, @johnfrancisgit, @lasfter - last reminder, please vote :)

@jflesch your code was already modified/rewritten at the time of your vote.

**Comment by int3l** [comment]
Also since the majority of the contributors agree with the license change, my proposal is to accept the petition and if there are any further objections by the above 4 contributors that still have unmodified/non refactored code, we can rewrite the code on case by case basis.

**Comment by jflesch** [comment]
>  if there are any further objections by the above 4 contributors that still have unmodified/non refactored code, we can rewrite the code on case by case basis.

Unfortunately, this is not how it works. If you publish their code under another license without their prior explicit agreement, they can sue you. So if they don't reply and you still want to change the license, you have to rewrite their code.

**Comment by int3l** [comment]
Well, I am aware of that, but I think that the chance of this happening is pretty much zero.
Also it might be relevant that most of the past contributions are co-authored/committed by me.
Matt has the final word though.

**Comment by h** [comment]
Aye!

**Comment by techtonik** [comment]
aye

**Comment by techtonik** [comment]
There is a possibility to object later given that the best effort was made to reach those folks. In case of rewrite I think it is fair to give credit anyway.

**Comment by streamnsight** [comment]
I did vote on the top comment. 👍

**Comment by int3l** [comment]
ok, sorry - so we just need: `nok` and `johnfrancisgit`

**Comment by ankutty** [comment]
aye

**Comment by nok** [comment]
@int3l Aye 👍

**Comment by madmaze** [comment]
Great, thanks @nok.

Just looking to hear back from @johnfrancisgit now, right?

**Comment by int3l** [comment]
Correct

**Comment by Orangeplumber** [comment]
Correct

**Comment by madmaze** [comment]
Great, thank you @int3l!

Yes, lets proceed with the license change, as soon as a new release is ready i can push it up to pypi.
