### ISSUE TITLE
Speed up pyTesseract

### ISSUE THREAD

**Issue by JJrodny** [madmaze/pytesseract#261]
Hi, so I'm trying to run pyTesseract on a number of images in python. I've noticed it takes about 500ms to run on one image, but I also noticed that I have to give it the language every time (or use whatever is the default language).

When I make the call `pytesseract.image_to_string(` does it load the language file each time? Is there a way to load the language file once, save my pytesseract instance in RAM (as a variable), and then call a similar `image_to_string` function that doesn't load the language file each time, and instead uses the one I loaded and saved into RAM?

Would this even improve the speed at all for inferencing multiple images?

I saw there's a way to batch process multiple files at once:
`# Batch processing with a single file containing the list of multiple image file paths
print(pytesseract.image_to_string('images.txt'))`

But I may not have all of the images at once, and I'd just like to speed up the pytesseract process, maybe by only loading the language file once?

What other ways are there to increase the speed of pytesseract?

Thanks!

**Comment by int3l** [comment]
At the moment, those are the available ways for speeding up the pytesseract.
Pytesseract is just a wrapper around the tesseract executable itself - so there is nothing fancy around it that can speed up the things. It is not a language binding for example.

You can use a list of images within a text file in order to make multiple images in batch. That's all at the moment - this is what pytesseract supports via the tesseract cli.

**Comment by Gornoka** [comment]
Your operating system may cache the Language file[s] for you, when repeatedly executing pytesseract. At least windows behaves this way. Multithreading the process could yield a higher execution speed depending on your system. OMP_THREAD_LIMIT is the environment variable that defines the number of threads used by tesseract ( Tess4.X) . You may reduce it to 1 and spawn an additional thread for every image you want to process. for example.
