### ISSUE TITLE
tests part of pypi tarball

### ISSUE THREAD

**Issue by pgajdos** [madmaze/pytesseract#262]
Could you please consider?

Thanks!

**Comment by int3l** [comment]
Yes, maybe we can have this via the setuptools extra `pip install pytesseract[dev]`?

**Comment by int3l** [comment]
Actually pytesseract's GitHub releases have the tests in it, so you can download the archive directly.
The actual pypi source is absolutely the same as the one from GitHub, because we use that to create the PyPi releases.

I am closing this issue, because previously, users requested the test data to be excluded from the PyPi package. And without test data, tests are useless :)
The other option with setuptools extras requires making separate package with the tests included, which is not viable.
