### ISSUE TITLE
image_to_string on tiff gives Warning: Metadata Warning, tag 283 had too many entries: 2, expected 1

### ISSUE THREAD

**Issue by Geraldf** [madmaze/pytesseract#287]
when I use the following code:

```
im = PI.open(os.path.join(fpath, fname))
txt = pytesseract.image_to_string(im)
print(txt)

```
I do get the following error on image_to_string
Warning: Metadata Warning, tag 283 had too many entries: 2, expected 1

**Comment by int3l** [comment]
This specific warning seems to be related to the Pillow library.
Can you share example tiff image that causes the warning?

**Comment by int3l** [comment]
This specific warning is generated by the Pillow Tiff Image Plugin on [Line 595](https://github.com/python-pillow/Pillow/blob/e5415ca082e9dbecb5f1c21650303b680ce6cadd/src/PIL/TiffImagePlugin.py#L595).
If you want to silence this warning, take a look at the [python's warnings module documentation](https://docs.python.org/3/library/warnings.html).
Or as a workaround, you should strip one of the 2 metadata tags from the image.
Closing this issue, since it's not a pytesseract specific one.

**Comment by Geraldf** [comment]
Hi @int3l,

thanks for your reply. Sure can I share the tiff showing the issue.

[f1_crop.tiff.zip](https://github.com/madmaze/pytesseract/files/4975829/f1_crop.tiff.zip)

Gerald

**Comment by int3l** [comment]
Thank you for supplying this sample.
I did some changes. you can try the latest version of pytesseract, when it's available and this warnings should be gone.
