### ISSUE TITLE
It always report OSError cannot write mode F as PNG when use image_to_string

### ISSUE THREAD

**Issue by cffznz** [madmaze/pytesseract#291]
We have code to user image_to_string with PIL and PNG format image, the code is availabe on 0.3.4, but in pytesseract 0.3.5, the code always failed with OSError: can not write mode F as PNG. the code as following:
           im = array(Image.open(filename).convert('L'))
           im2 = (100.0/255) * im + 100
           text = pytesseract.image_to_string(im2, lang='chi_sim', config='--oem 2 --psm 11')

This code can be run pass on pytesseract 0.3.4, but on pytesseract 0.3.5, it always report OSError: cannot write mode F as PNG

**Comment by int3l** [comment]
Hi, @cffznz - thank you for reporting the issue.
This error seems to be related to this change b22eaa43cfa4da119352847d6b75033aed66f95e .
Pytesseract doesn't convert images anymore in order to overcome similar errors.
This was done in order to allow more control for the users and to omit implicit conversions.

In your case, you can convert the image to one that is supported - for example, you can try to convert it back to RGB.

**Comment by cffznz** [comment]
Hi, thank you for your response. 
I have a question, currently, we use the image with PNG format, normally, the value of image.mode is RGBA
Does it still need to convert to RGB?
And could I know which version will be planned to resolve this issue? currently we will not set the version of pytesseract in out environement setup. But after find this issue and know the root cause, we need to define the old verison in our environement setup. And we want to know when or which version will be close this issue?

Thank you very much.

**Comment by int3l** [comment]
Hi,
It is always recommended that you pin the version for production usage.
I don't plan to fix this implicit conversion. It is in the hands of the user to decide, which format wants to convert to from now on.
About the RGBA - this logic is still present, because it is a straight forward conversion from single mode RGBA to RGB (stripping the Alpha band/channel).
