### ISSUE TITLE
zombies

### ISSUE THREAD

**Issue by devkral** [madmaze/pytesseract#294]
Sometimes tesseract spawns subprocesses. This causes timeouts which use SIGKILL, to leave the child processes in a zombie state.
I know upstream python uses the same technique but it has also this problem.
This behaviour is especially visible in docker containers (even with init shell).

One way to solve this problem would be a victim process which terminates itself after timeout and killing subprocesses with SIGKILL.

**Comment by int3l** [comment]
Hi @devkral 
Interesting, but this seems like tesseract related issue. It will be really ugly and hacky if third-party wrapper handles zombie processes of tesseract. For containers the following solution might work: custom detection of zombie process after the execution is done. And since the execution is isolated and controlled entirely, you can be sure that you are not going to kill any other legit tesseract process which is working in background.

My suggestion is to address this directly in tesseract itself. For example - with additional argument that ensures proper cleanup upon receiving SIGTERM/SIGKILL.

**Comment by devkral** [comment]
I found a solution: to rewrite kill this way:
`def kill(process, code):
    process.terminate()
    try:
        process.wait(1)  # or so, I used 5 to be sure
    except subprocess.TimeoutException:
        process.kill()
    process.returncode = code`

**Comment by devkral** [comment]
I think maybe it it is enough to dispatch the term signal first

**Comment by int3l** [comment]
@devkral Nice! Thank you for testing this, I will try to add this, but we will need a way to reproduce the child process spawn.
How did you manage to repro this? Using the batch function or?

**Comment by int3l** [comment]
Unfortunately [Popen.wait with timeout](https://docs.python.org/3/library/subprocess.htmlhighlight=popen#subprocess.Popen.wait) is Python 3 only. The python 2 user base is still at 5-8% - I guess that pytesseract will support python 2 until the end of this year.

**Comment by devkral** [comment]
of course does "terminate" not terminate the child process, it sends just a TERM signal so the cleanup process is started before we kill hard. here the adapted fix (python2 compatible):
```
def kill(process, code):
    process.terminate()
    try:
        process.wait(1)  # or so, I used 5 to be sure
    except TypeError:  # python2 fallback
        time.sleep(1)
        process.kill()
    except subprocess.CalledProcessError:
        process.kill()
    process.returncode = code

```

**Comment by devkral** [comment]
not a beauty but should work

**Comment by int3l** [comment]
Yeah, it's ugly as hell, but I hope that all of this will be gone next year :)
