### ISSUE TITLE
Pytesseract is not able to detect hyphen and instead shows 7

### ISSUE THREAD

**Issue by rutanshuj** [madmaze/pytesseract#299]
I have an image which has a string that I need to extract. The image is given below:

![](https://i.stack.imgur.com/bUtF5.jpg)

I need to take the text => '2145-3'

My code looks like this:

main.py
```
import pytesseract
import os

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract'
directory = './images'
for filename in os.listdir(directory):
    if filename.endswith((".jpg", ".JPG")):
        txt = pytesseract.image_to_string(directory+'/'+filename, lang='eng')
        print(txt)
```

The output:

```
Dhs. 90.00/ Dzn

214573
151 ADVENTURE STORIES

48 PCS / CTN

```

I have checked online and most of the answes were redirecting to the resoltion or shape of the image. I did change them, however the same result came up. This same issue happens with all the other images that are present in the directory as well.

**Comment by int3l** [comment]
Hi @rutanshuj this seems like an accuracy issue related to tesseract itself.
Tesseract has [trained data files](https://github.com/tesseract-ocr/tessdata) that in conjunction with the different tesseract config settings may produce different results.

So you can try to improve your accuracy with a better trained data files or with different image preprocessing techniques in order to get the proper result.

Unfortunately this is not a pytesseract specific issue. Pytesseract is just a simple wrapper/interface for interacting with tesseract itself. Maybe StackOverflow can help more with suggestions about improving the accuracy of recognizing symbols with tesseract.

**Comment by rutanshuj** [comment]
Hey @int3l  

Actually I have asked on Stack Overflow ([here](https://stackoverflow.com/questions/63980350/pytesseract-is-not-able-to-detect-hyphen-and-instead-shows-7)) and not yet got a response yet. However I will check out with different trained data files. 

Thank you for your suggestions and guidance 👍

**Comment by int3l** [comment]
I didn't help much, but I hope that someone with more tesseract experience will be able to help you via SO (a lot more ppl hang there). And be sure to add the `tesseract` tag as well, so more ppl can see it.
Closing this issue since it's not pytesseract specific. Feel free to reopen it or create a new one.

**Comment by bedna-KU** [comment]
Sometimes changing the dpi can help.
For example:
`config_ocr = r'-l eng --dpi 300'`

**Comment by int3l** [comment]
Yep, but the actual image dpi matters the most if I am not mistaken.

**Comment by bedna-KU** [comment]
Everything about AI is magic :)
