### ISSUE TITLE
Detect font style attributes

### ISSUE THREAD

**Issue by alexgg94** [madmaze/pytesseract#305]
Hi, 
I'm using **image_to_data** method to extract text from images and organize it into a pandas dataframe.
I was just wondering if there is any way to make **image_to_data** method also give me information about the word font style attributes (bold, italic, font size...).

Cheers

**Comment by int3l** [comment]
HI @alexgg94 
Is it possible for tesseract itself to report this information via additional option or configuration?
Because pytesseract is just a wrapper and if tesseract doesn't support this option itself, it will be a lot harder to implement additional logic to provide this attributes.

Another downside could be, that extracting additional information like font attributes may require executing **tesseract** multiple times, which can make **image_to_data** very slow.

**Comment by alexgg94** [comment]
Hi,

Tesseract itself can provide this logic by using _WordFontAttributes_ method defined in _ResultIterator_. 
I agree that this functionality could penalize time wise, but if somehow, it could be used along side **image_to_data** it would be so cool.

Just wondering if pytesseract right now can offer this feature or if it has been considered somehow.

PD. **image_to_data** makes my life so much easier, that's why I'm asking 😄 

Cheers

**Comment by int3l** [comment]
It seems that there is a problem with **WordFontAttributes** in the new engine: https://github.com/tesseract-ocr/tesseract/issues/1074
