### ISSUE TITLE
Open using PIL.image or file path

### ISSUE THREAD

**Issue by danilocorrea87** [madmaze/pytesseract#315]
Hello guys, I'm sorry if this is a silly question, I'm new here.

When I use pytesseract by passing an image path or using PIL.image, I get a different result in the text that was extracted.
Depending on the case, the PIL image returns a better result, or passing the direct image path is sometimes better.

I was wondering if there is an article explaining this, when should I follow one or the other?

Thanks.

**Comment by int3l** [comment]
Hi @danilocorrea87
results could differ, because passing the file path as string will bypass any processing by the PIL library or the pytesseract itself.
The only thing that pytesseract do before passing the image to tesseract is to remove the alpha channel in transparent images (aka transparent png files for example).
So this is why you could have different results sometimes. But unfortunately - there is no perfect way to predict, which way will yield better results, because this is OCR overall. Accuracy may vary because of multiple factors.

**Comment by danilocorrea87** [comment]
Thank you very much for the reply @int3l int3l

I'm using the fuzzy library to read the text from the OCR, I think I'll run both scenarios and end up getting the best result generated =)

Still thanks for the reply.
