### ISSUE TITLE
Facing issue while extracting bounding boxes using pytesseract

### ISSUE THREAD

**Issue by SiddhiK-bit** [madmaze/pytesseract#328]
Facing issue while scanning an image to extract details. All the details in the image below cannot be extracted using tesseract 
as bounding boxes cannot be formed on every text detail.

Line details are also not being extracted as no bounding box is getting  detected for it.

Images without bounding box:
![Image9](https://user-images.githubusercontent.com/79372419/108603512-4c919a80-73ce-11eb-960b-994efca196cd.jpg)
![Image8](https://user-images.githubusercontent.com/79372419/108603546-8e224580-73ce-11eb-896a-d28f7a891e96.jpeg)

Images with bounding boxes:

![image19 jpeg](https://user-images.githubusercontent.com/79372419/108603464-02101e00-73ce-11eb-9300-8110cecd1edf.png)

![image20](https://user-images.githubusercontent.com/79372419/108603154-439fc980-73cc-11eb-8ad4-69a25f7cca26.jpeg)

In image 19, all other details are extracted except cheque date and cheque amount.
Also, the  output image zooms out automatically which leads to certain details not getting detected.

In image 20, the bounding boxes are formed irregularly in few cases and for other text details they aren't formed.

**Comment by int3l** [comment]
Hi @SiddhiK-bit ,
this issue seems related to tesseract itself and not specifically to pytesseract.
Do you have the same inconsistent results while using tesseract itself directly without pytesseract?

You can try to pass the source image as string path of the file. For example:
```python
pytesseract.image_to_boxes('/path/to/example/image/file.jpg', ...)
```
This way you will ensure that pytesseract will skip any internal conversions.

**Comment by int3l** [comment]
Hi @SiddhiK-bit ,
this issue seems related to tesseract itself and not specifically to pytesseract.
Do you have the same inconsistent results while using tesseract itself directly without pytesseract?

You can try to pass the source image as string path of the file. For example:
```python
pytesseract.image_to_boxes('/path/to/example/image/file.jpg', ...)
```
This way you will ensure that pytesseract will skip any internal conversions.

**Comment by bedna-KU** [comment]
Try this
![Image_screenshot_21 02 2021](https://user-images.githubusercontent.com/4377084/108624264-2c042780-7444-11eb-9b21-bb7abe6f044e.png)

```
#!/usr/bin/env python3

import cv2
import pytesseract
from pytesseract import Output

def detector_text (image):
	config_ocr = r'--psm 11 --dpi 300'
	data = pytesseract.image_to_data(image, config=config_ocr, output_type=Output.DICT)

	window_name = 'Image'
	n_boxes = len(data['level'])
	for i in range(n_boxes):
		(x, y, w, h, conf, text) = (data['left'][i], data['top'][i], data['width'][i], data['height'][i], data['conf'][i], data['text'][i])
		if text:
			print(text, ">>> CONF:", conf)
			cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)

	# Displaying the image
	cv2.imshow(window_name, image)
	cv2.moveWindow(window_name, 0, 0)
	k = cv2.waitKey(0)

image = cv2.imread("image.jpg")
detector_text(image)
![Image_screenshot_21 02 2021](https://user-images.githubusercontent.com/4377084/108624250-12fb7680-7444-11eb-8a2c-c7a7a0427bf6.png)

```
