### ISSUE TITLE
pytesseract uses a broken release of Tesseract

### ISSUE THREAD

**Issue by wfreeman-IU** [madmaze/pytesseract#345]
pytesseract uses Tesseract 4.0.0 which is known to have problems such as coming with a broken version of: 
/usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata 
(~3MB)
which needs to be manually replaced with: 
https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata 
(~22MB+)
as discussed here:
https://stackoverflow.com/questions/2363490/limit-characters-tesseract-is-looking-for
and elsewhere.
If it could be updated to 4.1.1 the problems should go away.

**Comment by int3l** [comment]
Hi @wfreeman-IU and thank for reporting this issue.
*pytesseract* itself uses whatever version you have installed locally, so you can install which ever you want.
You need to adjust your setup and install the Tesseract version that works for your setup.

Closing this one since it's not a `pytesseract` related issue, but `tesseract-ocr` one.
