### ISSUE TITLE
IOError: cannot write mode LA as BMP

### ISSUE THREAD

**Issue by tadamhicks** [madmaze/pytesseract#35]
This directly from PIL.
I am trying to run this very basic against a single file in the same directory.  Won't work.

Python 2.7 Mac OS X.

**Comment by senderle** [comment]
I got the same error when using `wand` to convert from PDF to TIFF. The result is a layered tiff (or at least that's what I guess "LA" stands for). When the script tries to save the file as a BMP, you get an error -- I suppose because BMP doesn't support layering? So the simple solution would be to save a tiff instead of a BMP. 

Seems like an easy fix. Why does `pytesseract` use BMPs instead of tiffs? Am I missing something?

**Comment by vitalk** [comment]
As workaround you can convert your image to `RGB`

```python
pytesseract.image_to_string(image.convert('RGB'))
```

**Comment by senderle** [comment]
Not lure what this would do to enable layering in BMP. Unless I'm mistaken, each layer is one page from the PDF. I'll give it a try and see what happens though.
