### ISSUE TITLE
Stripped "\" from Windows Tessdata Path

### ISSUE THREAD

**Issue by tallsmallone** [madmaze/pytesseract#356]
When trying to run pytesseract from a windows 10 environment, I found that the config was stripping the `\` in my tessdata path.

I found that the solution to fix this was in pytesseract.py: line 251:
>if config:
        cmd_args += shlex.split(config, posix=False)

To confirm it was the issue, here was the config before this section of code:
`--tessdata-dir E:\Projects\fhm-test-automation\tessdata --oem 3 --psm 3`

And after the shlex.split(), the cmd_args was now:
`['tesseract', 'C:\\Users\\nickr\\AppData\\Local\\Temp\\tess_ai78chdv.PNG', 'C:\\Users\\nickr\\AppData\\Local\\Temp\\tess_ai78chdv', '-l', 'eng', '--tessdata-dir', 'E:Projectsfhm-test-automationtessdata', '--oem', '3', '--psm', '3']`

Please note that I truncated off the extra, unneeded information.

As you can see, the `--tessdata-dir` was altered, thus giving the dreaded `TESSDATA_PREFIX` error.

I would make a PR myself, but I do not know enough about the system to know the consequences on my actions.

**Comment by int3l** [comment]
Hi @tallsmallone 
Thank you for reporting the issue.
This seems like a platform specific bug.
For reference, this is how `numpy` does the parsing: https://github.com/numpy/numpy/blob/main/numpy/distutils/_shell_utils.py
Maybe we can use some built-in for solving this.

**Comment by KanakaJack2** [comment]
"service error: OCR error: (1, 'Error opening data file "C:/Users/Brendon Bauelua/Documents/DevTools"/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract.')"

Please see the above, I think the issue is similar. Pytesseract is not parsing the correct file path, see how the quotes only keep certain file path secured for reading then the .engtrainned data
