### ISSUE TITLE
Could you please explain one sentence in README.md more clear?

### ISSUE THREAD

**Issue by JamesRaynor67** [madmaze/pytesseract#380]
> Note: Make sure that you also have installed tessconfigs and configs from tesseract-ocr/tessconfigs or via the OS package manager.

What's the meaning of install configs here? Could you please add instructions to do it? Also, why is this needed? Thank you!

**Comment by int3l** [comment]
I believe that this was related to the older versions of tesseract. For example you can check this repository with various configs -- https://github.com/tesseract-ocr/tessconfigs
Some of those configs were excluded from the main tesseract package, which meant that you needed to install them separately.
In order to install them you either need to use the OS specific package that contains them or manually copy them to a specific directory.

If you don't use any fancy tesseract configurations, you don't need to worry about this note.
I will change the wording a bit for this section or order to avoid the confusion.
