### ISSUE TITLE
Question: Tesseract without install

### ISSUE THREAD

**Issue by tonylanglet** [madmaze/pytesseract#396]
Hello,
This might not be the first time this question have come up, but I do have a discord bot running on a bot server (limited) I'm not able to install any external packages except for what can be found on pypi, so I'm not able to install the exe file and run tesseract from the server.

I did read somewhere the the tesseract-orc-data might be able to provide me with this functionality, so I'm asking the experts of the matter, is there a way for me to run the pytesseract without having to install the exe file on a server?

Thanks for making this...

**Comment by int3l** [comment]
if you can install the pytesseract, then you have some sort of local access. One way to workaround around that is to check the host architecture and to copy the binary files of tesseract itself to the same server.
I don't know if there is packaged tesseract distro via pypi directly - and honestly, this package is not focused on that.
Maybe you can have a better success with another similar package, which tries to integrate with the tesseract library: https://github.com/sirfz/tesserocr (but it might need installing additional dependency as well).

Closing this one since it's not pytesseract related issue and this is an issue tracker.
You might get better answer on StackOverflow :)
