### ISSUE TITLE
Is it Possible to Extract Hand written dates?

### ISSUE THREAD

**Issue by pavankalyan066** [madmaze/pytesseract#414]
Hello,

I'm trying to extract the handwritten dates from the cropped portion of the image, but my result is not satisfactory.

I would like to know whether it is an issue with my document or model.

**Sample Image below**
![image](https://user-images.githubusercontent.com/30195057/156361764-9216f5ad-5ce4-4468-b5b4-f2c8834fac78.png)

**Arguments:** data = pytesseract.image_to_string(letter, lang='eng', nice=0,config=custom_oem_psm_config)

**Result:**  'ae eat\nCOMPLETED: 2520),\n\x0c'

**Comment by int3l** [comment]
@pavankalyan066 this is not very suitable task for tesseract unless you train tesseract explicitly on handwritten text.
Tesseract was created to extract text from scanned books and not human written text.
Closing this, since it's not a pytesseract related issue (this is the issue tracker, please as such questions on StackOverflow, thanks).
