### ISSUE TITLE
How to use tessdata in pytesseract.

### ISSUE THREAD

**Issue by ahmadmustafaanis** [madmaze/pytesseract#427]
How to use tessdata in pytesseract.

Code:
```
import cv2

img = cv2.imread('/home/ahmad/Pictures/Screenshot from 2022-04-28 11-47-48.png')
start = time.time()
data = pytesseract.image_to_boxes(img, lang='eng',config='--psm 6 --tessdata-dir /home/ahmad/Desktop/RedBuffer/RealTimeOCRTest/tessdata_data')
print(time.time()-start)
h, w, c = img.shape
for b in data.splitlines():
    b = b.split(' ')
    frame = cv2.rectangle(img, (int(b[1]), h - int(b[2])), (int(b[3]), h - int(b[4])), (0, 255, 0), 2)

plt.imshow(frame)
```

Error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_inhosyge.box'
```

Everytime I run I get different file error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_wn1sgerd.box'
```

**Comment by caerulescens** [comment]
1. If you're going to ask for help, provide a complete example; you're missing imports in your code snippet.
2. Provide an example image; sometimes the error could be generated by the specific image. In this case, it doesn't relate to the image. 
3. Instead of using `--tessdata-dir`, you should set the `TESSDATA_PREFIX` environment variable; regardless, it works both ways. 
4. Your `tessdata` folder is configured incorrectly; I ran your code snippet and it runs without error. 

You forgot to initialize the git sub-module containing the configurations, which are stored in a different repository because it's shared between `tessdata`, `tessdata_fast`, and `tessdata_best`.

How-to configure the tessdata:
```
git clone https://github.com/tesseract-ocr/tessdata
git submodule init
git submodule update
```

**Comment by caerulescens** [comment]
@int3l Can you please close this. Thanks.

**Comment by int3l** [comment]
@ahmadmustafaanis , a far better place to ask for similar questions is [StackOverflow](https://stackoverflow.com/). A lot more people go there for help and answers such this one from @caerulescens can be useful for someone else as well.

This issue trackers is just for issues related to the pytesseract project itself.
Thanks
