### ISSUE TITLE
KeyError: 'PNG' while using pytesseract.image_to_data

### ISSUE THREAD

**Issue by daniel-xion** [madmaze/pytesseract#444]
I tried to put boxes in an image file around the texts in it, using pytesseract function image_to_data, but encounters the following error on Google colab (pip installed pytesseract dist-packages (0.3.9)):

```
KeyError                                  Traceback (most recent call last)
<ipython-input-10-a92a28892aac> in <module>()
      6 img = cv2.imread("a.jpg")
      7 
----> 8 d = pytesseract.image_to_data(img, output_type=Output.DICT)
      9 print(d.keys())

5 frames
/usr/local/lib/python3.7/dist-packages/PIL/Image.py in save(self, fp, format, **params)
   2121         expand=0,
   2122         center=None,
-> 2123         translate=None,
   2124         fillcolor=None,
   2125     ):

KeyError: 'PNG'
```
The code I am using is :

```
import cv2
import pytesseract
from pytesseract import Output
from PIL import Image

img = cv2.imread("a.jpg")

d = pytesseract.image_to_data(img, output_type=Output.DICT)
print(d.keys())
```

It also gives the same error when the image is in png format.

**Comment by stefan6419846** [comment]
Your stacktrace seems to miss some lines, but I suspect that the culprit is https://github.com/madmaze/pytesseract/blob/479674e78dd2b103b169dceaba8cd553bd24140e/pytesseract/pytesseract.py#L199 Judging from the code and the fact that you state that the *KeyError* always is about PNG, the format detection in https://github.com/madmaze/pytesseract/blob/479674e78dd2b103b169dceaba8cd553bd24140e/pytesseract/pytesseract.py#L176 might have an edge case.

Have you tried passing the image path directly? Have you tried opening the image file with *Pillow* and passing this directly? Does this result in any issues? Are you able to provide a reproducing example image?
