### ISSUE TITLE
Error when trying to import pytesseract

### ISSUE THREAD

**Issue by graham-eisele** [madmaze/pytesseract#453]
I am getting the following error when trying to import pytesseract:

```ModuleNotFoundError: No module named 'pytesseract'```

I am using windows 11 and I made sure to have tesseract in my path and it works when I call it directly from the command prompt. I am using python > 3.6 like it says in the instructions.

**Comment by stefan6419846** [comment]
Besides installing the Tesseract package itself, you have to make sure to install *pytesseract* as well of course for the used Python interpreter. Instructions are given in the README at https://github.com/madmaze/pytesseract#installation. Are you sure you actually installed the Python package through *pip*?

**Comment by Graham956** [comment]
Yes, I installed it using `pip install pytesseract` and it successfully installed.

**Comment by stefan6419846** [comment]
As I am not aware of any similar reports, I assume that there is something wrong with your setup.

What Python version are you using? How did you install it? What is the actual output of calling `pip install pytesseract`? Do you have multiple Python versions on your system? What is the output of using `python -m pip show pytesseract` where `python` is the same binary as you use for running your actual code? What happens if you use `pip install` with any other PyPI package and try to import these inside your code?
