### ISSUE TITLE
Orientated text detection

### ISSUE THREAD

**Issue by Rohinivv96** [madmaze/pytesseract#497]
I am attempting to implement tesseract for an image with varying text orientations such as 90, 180, or 270 degrees. I am utilizing the "image_to_string" function to detect the text and transfer it onto a blank image. However, during the extraction process, "image_to_string" automatically adjusts the orientation angle of the text and provides the text aligned at 0 degrees. Nonetheless, for my specific scenario, it is essential to extract the text as it is, without any correction of the text orientation prior to extraction. Is there a method available to obtain the text in its original form without rotating it to the corrected orientation angle?

Thank you.

**Comment by stefan6419846** [comment]
*pytesseract* never changes any text orientation - this is something which is caused by Tesseract and therefore most likely not a *pytesseract* issue, so the wrong place to request a change here.

You might want to try `image_to_pdf_or_hocr` instead with `extension='hocr'`, which will contain information for rotated text when the text is rotated:

```html
...
<span class='ocr_line' id='line_1_54' title="bbox 66 2798 88 3436; textangle 90; x_size 23.242424; x_descenders 5.810606; x_ascenders 5.810606">
...
```

Tesseract (more or less) follows the hOCR standard available from http://kba.github.io/hocr-spec/1.2/
