### ISSUE TITLE
windows 10 :pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/chi_sim.traineddata')

### ISSUE THREAD

**Issue by zwl1619** [madmaze/pytesseract#50]
I am using pytesseract on windows 10 x64, and the python is `3.5.2` x64, Tesseract is `4.0` ,the code is as follow:

```
# -*- coding: utf-8 -*-

try:
    import Image
except ImportError:
    from PIL import Image
import pytesseract


print(pytesseract.image_to_string(Image.open('d:/testimages/name.gif'), lang='chi_sim'))

```
error:
```
Traceback (most recent call last):
  File "D:/test.py", line 10, in <module>
    print(pytesseract.image_to_string(Image.open('d:/testimages/name.gif'), lang='chi_sim'))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 165, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/chi_sim.traineddata')
```
`C:\Program Files (x86)\Tesseract-OCR\tessdata`,like this:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/TwwEo.png

**Comment by int3l** [comment]
@zwl1619 This is not a pytesseract issue. It is a Tesseract-OCR related problem.
You have to install the additional train data for your specific language preference.
For example, the Tesseract-OCR Installer for Windows have additional language options for selecting during installation. Try to select some of them, which are specific for your language needs.

**Comment by dodo4910** [comment]
I have same condition. Change lang item is no useful

**Comment by dodo4910** [comment]
In win7 have same condition

**Comment by jtbr** [comment]
This occurs under windows (at least in tesseract version 3.05) when the current directory is on a different drive from where tesseract is installed.

Something in tesseract is expecting data files to be in \\Program Files... (rather than C:\\Program Files, say). So if you're not on the same drive letter as tesseract, it will fail. It would be great if we could work around it by temporarily changing drives (under windows only) to the tesseract installation drive before executing tesseract, and changing back after.

**Comment by int3l** [comment]
@jtbr thanks for the explanation, I will try to reproduce this error behavior.
However I'm not sure if we can fix it within pytesseract.

**Comment by int3l** [comment]
Please check this issue for solution: #55

**Comment by jtbr** [comment]
@int3l This issue not user error like #55. The error occurs in tesseract itself:
`pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/eng.traineddata')`

It can be worked around by changing directory to the drive containing tesseract, but not by customizing `pytesseract.pytesseract.tesseract_cmd` unfortunately.

**Comment by int3l** [comment]
Unfortunately I can't reproduce this error. I will try once again.
Maybe I should install tesseract on a different drive as well.

**Comment by coollorenzo** [comment]
Same problem here using windows 10 64bit and python2.7 32bit `pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\tesseract-ocr\\tessdata/eng.traineddata')`

**Comment by int3l** [comment]
@zwl1619, @coollorenzo,
Finally managed to reproduce this error.

Please try to use the config option with pytesseract like this:
```python

tessdata_dir_config = '--tessdata-dir "<replace_with_your_tessdata_dir_path>"'
# Example config: '--tessdata-dir "C:\\Program Files (x86)\\Tesseract-OCR\\tessdata"'
# It's important to include double quotes around the dir path.

pytesseract.image_to_string(image, lang='chi_sim', config=tessdata_dir_config)
```

If this workaround works for you, I will include the snippet to the README file.

**Comment by jfchavez** [comment]
@zwl1619 Your solution worked for me (as well as changing the path as suggested by @jtbr) Many thanks!

**Comment by PaniniGelato** [comment]
worked for me! thank u very much!

**Comment by xiaoermaomao** [comment]
@zwl1619 @int3l  Thanks ，it works！

**Comment by SriSk87** [comment]
I have the same error but my python is throwing just this
`TesseractError: (1, '')`

what is the solution for this

**Comment by int3l** [comment]
@SriSk87 Run **tesseract** directly and check what is going on. TesseractError means that something bad happened inside the tesseract itself. If there is an error, you can report it.

**Comment by mhalomari** [comment]
Hi, I added the following lineto my python code and it works
`pytesseract.pytesseract.tesseract_cmd = 'C:\Program Files (x86)\Tesseract-OCR\\tesseract.exe'`
You have to install Tesseract-OCR first (https://digi.bib.uni-mannheim.de/tesseract/).

**Comment by jdpos** [comment]
Thanks jtbr! I was in F:\.

**Comment by miss570** [comment]
Why is my setup the same?

**Comment by miss570** [comment]
Seeking answers

**Comment by brunomns** [comment]
I was facing something similar.
The problem was on the version of tesseract. I was trying to use a 32bit version. Getting the right version (for 64bit) here:  (https://digi.bib.uni-mannheim.de/tesseract/). Instaling and seting up TESS_DATA path was the soluiton! Now it is running smooth! thanks for the link @mhalomari!

**Comment by gakshat1107** [comment]
Nothing is working for me. Anyone please help.
My email - gakshat1107@gmail.com

**Comment by AVI18794** [comment]
https://github.com/madmaze/pytesseract/issues/50#issuecomment-301553416
This worked for me while now the problem is what if I want to pass multiple values to the config how will one do that.
I checked the environment variables and set the path correctly however while I am trying to run this there is a same error.
and with the solution given at https://github.com/madmaze/pytesseract/issues/50#issuecomment-301553416
how can one pass several parameters to the config like in case of I want to detect only digits lets say while doing OCR.
![image](https://user-images.githubusercontent.com/37730987/105521695-3d9dc680-5d02-11eb-9f47-f46b12e92d73.png)

**Comment by M007-lab** [comment]
In my case the fra.traineddata was missing in the folder, so I had to download it directly from github https://github.com/tesseract-ocr/tessdata/blob/master/fra.traineddata then place it in the tessdata folder manually !

**Comment by stefan6419846** [comment]
Have you tried using these options with plain Tesseract? Does it work?

**Comment by 1mouSYS** [comment]
what about this error PLZ

TesseractError: (1, 'Error opening data file C:\\Program Files (x86)\\Tesseract-OCR\\eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

**Comment by stefan6419846** [comment]
Does the aforementioned directory contain the `eng.traineddata` file?

**Comment by 1mouSYS** [comment]
@stefan6419846   yes eng.trainedata file  in tessdata .

**Comment by stefan6419846** [comment]
What happens if you run `tesseract.exe --list-langs` from the terminal?

In my case, I am on Linux and the `TESSDATA_PREFIX` environment variable has to point to the `tessdata` directory, as documented inside the FAQ as well (https://tesseract-ocr.github.io/tessdoc/FAQ.html#where-are-the-language-models-traineddata-files-for-tesseract-installed):

```bash
stefan@localhost:~> TESSDATA_PREFIX=/usr/share/tesseract-ocr/4/tessdata tesseract --list-langs
List of available languages (4):
deu
eng
frk
osd
stefan@localhost:~> TESSDATA_PREFIX=/usr/share/tesseract-ocr/4 tesseract --list-langs
Error opening data file /usr/share/tesseract-ocr/4/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
List of available languages (4):
tessdata/deu
tessdata/eng
tessdata/frk
tessdata/osd
```

**Comment by 1mouSYS** [comment]
when i run this command
C:\Program Files\Tesseract-OCR>tesseract.exe --list-langs
this is results
List of available languages in "C:\Program Files
(x86)\tesseract-OCR\tessdata/" (0):
