### ISSUE TITLE
Access is denied(Windows 10, Python2.7/3.5)

### ISSUE THREAD

**Issue by sniranjan** [madmaze/pytesseract#55]
I am getting access denied error when trying to do basic operation.
I downloaded the windows version of tesseract from [here (UB-Mannheim, : tesseract-ocr-setup-3.05.00dev.exe)](https://github.com/UB-Mannheim/tesseract/wikihttps://github.com/UB-Mannheim/tesseract/wiki)

Tried moving tesseract from C to D drive, didn't help.

```
try:
    import Image
except ImportError:
    from PIL import Image
import pytesseract
pytesseract.pytesseract.tesseract_cmd = 'C:\Program Files (x86)\Tesseract-OCR'
x = pytesseract.image_to_string(Image.open('cropped.png'))
```

**Comment by int3l** [comment]
Hi, @sniranjan 
Try to use [administrative command prompt (console) on Windows 10](http://winaero.com/blog/how-to-open-elevated-command-prompt-in-windows-10/).
If this works, then you have permission issue and in this case you should tweak the Win 10 file and folder permissions for the Tesseract executable in order to make it work without administrative prompt.

**Comment by int3l** [comment]
I tested your case, please try to use the following code instead, because your variable is not correct:
`pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract.exe'`
