### ISSUE TITLE
TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by msean** [madmaze/pytesseract#56]
there happens error when i run the code:
```
from PIL import Image
import pytesseract

im1_path = r"D:\pictures\8.png"
image = Image.open(im1_path)
captcha_code = pytesseract.image_to_string(image)
print(captcha_code)
```
traceback:
```
Traceback (most recent call last):
  File "D:/python_workplace/Learn-to-identify-similar-images-master/similarity.py", line 5, in <module>
    captcha_code = pytesseract.image_to_string(image)
  File "C:\Python34\lib\site-packages\pytesseract\pytesseract.py", line 163, in image_to_string
    errors = get_errors(error_string)
  File "C:\Python34\lib\site-packages\pytesseract\pytesseract.py", line 111, in get_errors
    error_lines = tuple(line for line in lines if line.find('Error') >= 0)
  File "C:\Python34\lib\site-packages\pytesseract\pytesseract.py", line 111, in <genexpr>
    error_lines = tuple(line for line in lines if line.find('Error') >= 0)
TypeError: 'str' does not support the buffer interface
```
what the problem may be here?

**Comment by int3l** [comment]
Hi @msean,
is it possible to provide the following information:
- your OS version
- Tesseract version and pytesseract version
- what Image library is in use and version: the old PIL or Pillow
- the image that produce this error, so we can test

**Comment by msean** [comment]
OS Version:win10
Tesseact exe:tesseract-ocr-setup-3.05.00dev.exe
pytesseract:0.1.6

you can choose the first picture download from:
https://www.google.com.hk/search?safe=strict&biw=2133&bih=1055&tbm=isch&sa=1&q=8&oq=8&gs_l=img.3..0l10.2116.2116.0.2601.1.1.0.0.0.0.335.335.3-1.1.0....0...1c..64.img..0.1.334.DXFatBeHaY8#imgrc=fI624G8fuvMegM
do a test

**Comment by int3l** [comment]
Hi @msean,
I installed the exact same versions as you, but I don't have this error, when I scan the first image with pytesseract.

Can you please click on the right button "View image" and copy-paste the URL link directly, so we can be sure that we are testing with the same images.

I tested with python 3.4.4 and 3.5.3.
Can't reproduce.

**Comment by fjt37** [comment]
@msean That's a bug in that version (0.1.6) of pytesseract. You can fix it by editing `C:\Python34\lib\site-packages\pytesseract\pytesseract.py` 
and adding the line
`error_string = error_string.decode('utf-8')`
before line 110 (at the beginning of the `get_errors` method)

Or you can clone this repo, because the bug has been fixed here.

**Comment by int3l** [comment]
Hi @fjt37,
interesting, so you can reproduce this behavior?
Because I tested with the original 0.1.6 version, and I couldn't produce the exception with the sample test image.

**Comment by fjt37** [comment]
I reproduced it by accident, and found this thread trying to fix it. The trick (for me) was that you need  Tesseract to write to stderr. `error_string` is split into lines, and then `find` is called on each line. The lines in release 0.1.6 were `bytes` instead of `str`s, so it raises the error msean saw. However, if `error_string` is empty then the `lines` list will empty so the find method is never called, thus no error.

For me, it was writing to stderr because I hadn't linked libjpeg properly when I installed Tensorflow. It therefore had nothing to do with the image.

**Comment by int3l** [comment]
Thanks for the clarification,
I will leave the issue open for a couple of days.

And for the fix - I will ping Matthias, because I don't have upload permissions on pypi, in order to release the new version.

**Comment by fjt37** [comment]
No problem, and thanks
