### ISSUE TITLE
Improve the result for small text

### ISSUE THREAD

**Issue by kamelbouyacoub** [madmaze/pytesseract#57]
Hello 

I am trying to use pytessaract for text detection in a GUI Swing java, the probleme is I don't know how to improve the result, and specialy when the font is small, please can i have some advice for that ?

Thanks,

**Comment by carlitoselmago** [comment]
I was dealing with the same problem, i just previously resized the text image with OpenCV and got much better results, at CPU cost of course.

**Comment by int3l** [comment]
@kamelbouyacoub This problem is not directly related to pytesseract.
You can try to train tesseract with sample images with small font.
Additional information/documentation for tesseract training: [Training Tesseract 4.00](https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#training-tesseract-lstm-engine)
