### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by yeshang0555** [madmaze/pytesseract#86]
Very grateful to the author to provide such a good library, but there is a problem during use, my encoding used in the console non-utf-8 encoding, resulting in abnormal return information, can not locate the real problem, it is recommended that the author will do coding A global variable, others can set their own encoding

**Comment by int3l** [comment]
Hello @yeshang0555 , Thank you very much for reporting the issue.
I was thinking about that aspect of the package too.
Maybe we can introduce encoding option for the current image_to_string function.

I am not sure if it's a good idea to use the global variables for implementing support for custom encoding, since this can affect use cases, where we have a mix of different encodings.
And it may be a problem in a multi-threaded/multi-process workflows.

**Comment by int3l** [comment]
Also keep in mind that from one side - you have the default encoding of your terminal/execution environment.
From another side, you have the default encoding for the python platform itself.
And from third side, you have the actual encoding of your data.

So you should consider all of them in order to ensure proper encode/decode operations and visualization for the tesseract output data.

**Comment by yeshang0555** [comment]
I am grateful to the author for the reply you gave me. I will think more about it and thank you very much.

**Comment by REMitchell** [comment]
This might be a good argument for optionally returning files objects, rather than just strings/dicts.

**Comment by int3l** [comment]
@yeshang0555 Thanks to @REMitchell, now you can use the byte output option in order to do custom decoding of the tesseract result.

Closing as fixed. Please feel free to reopen the issue if you have anything else to add.
